test1: test1.cpp c_tokenizer1.c
	g++ -o test1 test1.cpp c_tokenizer1.c -I../../include -O3 -ggdb
test2: test1.cpp c_tokenizer2.c
#	g++ -o test2 test1.cpp c_tokenizer2.c -I../../include -O0 -ggdb
	g++ -o test2 test1.cpp c_tokenizer2.c -I../../include -O3 -ggdb
test3: test1.cpp c_tokenizer3.c
	g++ -o test3 test1.cpp c_tokenizer3.c -I../../include -O3 -ggdb
