#ifndef TAP_RDS_BGD_SIMULATOR_H
#define TAP_RDS_BGD_SIMULATOR_H

#include <cstdint>
#include <string>
#include <vector>

#include "cluster_simulator.h"
#include "utils.h"

using namespace std;

/**
 * @brief Represents one row returned by the simulated `mysql.rds_topology` table.
 */
struct RDS_BGD_Topology_Row {
	string id;        ///< RDS topology node identifier.
	string endpoint;  ///< RDS hostname exposed by the topology row.
	int port;         ///< MySQL port exposed by the topology row.
	string role;      ///< Blue/green deployment role reported by RDS.
	string status;    ///< Blue/green deployment status reported by RDS.
};

/**
 * @brief Describes one RDS BGD host and its fixed simulator address.
 */
struct RDS_BGD_Host {
	string hostname;  ///< AWS-style RDS hostname configured in ProxySQL.
	string ip;        ///< Fixed loopback address used by the simulator.
	int port;         ///< MySQL listener port shared by the hostname and IP.

	/**
	 * @brief Returns the IP/port endpoint used for topology simulation.
	 *
	 * @return Simulator endpoint containing this host's IP address and port.
	 */
	Endpoint endpoint();

	/**
	 * @brief Returns the hostname/port endpoint used for read-only simulation.
	 *
	 * @return Simulator endpoint containing this host's RDS hostname and port.
	 */
	Endpoint host_endpoint();
};

/**
 * @brief Holds the blue and green hosts participating in one simulated RDS BGD cluster.
 *
 * @details TAP tests populate the cluster with the deployment topology required by each
 *   scenario. Helper methods derive writer endpoints and AWS topology rows from
 *   the configured hosts.
 */
class RDS_BGD_Cluster {
public:
	RDS_BGD_Host blue_writer;          ///< Source writer configured in ProxySQL.
	RDS_BGD_Host green_writer;         ///< Target writer discovered from the topology.
	vector<RDS_BGD_Host> blue_readers;  ///< Source readers configured in ProxySQL.
	vector<RDS_BGD_Host> green_readers;  ///< Target readers discovered from the topology.

	/**
	 * @brief Returns both writer IP/port endpoints for topology simulation.
	 *
	 * @return Blue and green writer endpoints keyed by simulator IP address.
	 */
	vector<Endpoint> get_writers();

	/**
	 * @brief Returns the blue writer and configured blue readers.
	 *
	 * @return Blue deployment endpoints keyed by simulator IP address.
	 */
	vector<Endpoint> get_blue_endpoints();

	/**
	 * @brief Returns the green writer and configured green readers.
	 *
	 * @return Green deployment endpoints keyed by simulator IP address.
	 */
	vector<Endpoint> get_green_endpoints();

	/**
	 * @brief Returns every simulator IP/port endpoint in this cluster.
	 *
	 * @details Includes both writers and all configured blue and green readers.
	 *   Tests use this list when resetting or publishing topology for a complete
	 *   simulated deployment.
	 *
	 * @return Writer and reader endpoints keyed by simulator IP address.
	 */
	vector<Endpoint> get_endpoints();

	/**
	 * @brief Builds the topology rows published by the simulated writers.
	 *
	 * @details Creates one source row for the blue writer and one target row for the green
	 *   writer. The supplied deployment status is applied to both rows.
	 *
	 * @param status RDS blue/green deployment status to publish.
	 *
	 * @return Source and target rows for the simulated topology table.
	 */
	vector<RDS_BGD_Topology_Row> get_topology(string status);
};

/**
 * @brief Identifies the RDS BGD monitor query recorded in the simulator probe log.
 */
enum class RDS_BGD_Probe_Kind {
	table_check,  ///< Query checking whether `mysql.rds_topology` exists.
	metadata,     ///< Query fetching rows from `mysql.rds_topology`.
};

/**
 * @brief Describes one RDS BGD monitor query observed by the simulator.
 */
struct RDS_BGD_Probe_Log {
	uint64_t sequence_id;             ///< Monotonically increasing probe-log sequence.
	Endpoint backend;                 ///< Accepted backend IP address and port.
	RDS_BGD_Probe_Kind probe_kind;    ///< Type of topology query observed.
	bool encrypted;                   ///< Whether the monitor connection used TLS.
};

/**
 * @brief Controls RDS BGD topology responses and inspects monitor probes from TAP tests.
 *
 * @details Publishes per-backend topology rows, empty results, missing tables, or MySQL
 *   errors. It also reads the ordered probe log generated by the SQLite3-server
 *   simulator and reuses `Cluster_Simulator` for shared control operations.
 */
class RDS_BGD_Simulator : public Cluster_Simulator {
public:
	/**
	 * @brief Replaces the simulated topology returned by each backend.
	 *
	 * @details Deletes existing topology rows before inserting the supplied rows. The
	 *   topology table is marked present, configured errors are cleared, and the
	 *   complete update is applied atomically across all supplied backends.
	 *
	 * @param backends Backend IP/port endpoints that must return the topology.
	 * @param rows Topology rows to publish on each backend.
	 *
	 * @return EXIT_SUCCESS when every backend is updated; EXIT_FAILURE otherwise.
	 */
	int topology_update(vector<Endpoint> backends, vector<RDS_BGD_Topology_Row> rows);

	/**
	 * @brief Configures each backend to return an empty topology result.
	 *
	 * @details Deletes all topology rows associated with the supplied backends while keeping
	 *   the topology table present and clearing any configured metadata error.
	 *
	 * @param backends Backend IP/port endpoints that must return an empty result.
	 *
	 * @return EXIT_SUCCESS when every backend is updated; EXIT_FAILURE otherwise.
	 */
	int topology_delete(vector<Endpoint> backends);

	/**
	 * @brief Configures each backend to report that the topology table does not exist.
	 *
	 * @param backends Backend IP/port endpoints that must return MySQL error 1146.
	 *
	 * @return EXIT_SUCCESS when every backend is updated; EXIT_FAILURE otherwise.
	 */
	int topology_drop(vector<Endpoint> backends);

	/**
	 * @brief Configures a MySQL error for topology queries on each backend.
	 *
	 * @details Stores the nonzero error code and message returned by subsequent metadata
	 *   probes. Error 1146 marks the topology table absent and removes its existing
	 *   rows; other error codes leave the table marked present.
	 *
	 * @param backends Backend IP/port endpoints that must return the error.
	 * @param error_code Nonzero MySQL error code to return.
	 * @param error_msg MySQL error message to return.
	 *
	 * @return EXIT_SUCCESS when every backend is updated; EXIT_FAILURE otherwise.
	 */
	int topology_error(vector<Endpoint> backends, int error_code, string error_msg);

	/**
	 * @brief Removes all read-only, topology-control, topology-row, and probe state.
	 *
	 * @return EXIT_SUCCESS when the simulator state is empty; EXIT_FAILURE otherwise.
	 */
	int cleanup();

	/**
	 * @brief Reads the latest sequence from the RDS BGD probe log.
	 *
	 * @return EXIT_SUCCESS and the latest sequence, or zero when the log is empty;
	 *   EXIT_FAILURE and zero when the query fails.
	 */
	rc_t<uint64_t> probe_log_last_sequence();

	/**
	 * @brief Returns probe-log records newer than a sequence.
	 *
	 * @details Selects records with `sequence_id` strictly greater than the supplied value
	 *   and preserves database sequence order in the returned vector.
	 *
	 * @param sequence_id Last probe-log sequence already observed by the TAP test.
	 *
	 * @return EXIT_SUCCESS and the matching records; EXIT_FAILURE and an empty vector
	 *   when the query or record parsing fails.
	 */
	rc_t<vector<RDS_BGD_Probe_Log>> probe_log_since(uint64_t sequence_id);

	/**
	 * @brief Waits for a matching RDS BGD probe-log record.
	 *
	 * @details Matches records newer than `sequence_id` by backend and probe kind. TLS state
	 *   is matched when `encrypted` is zero or one; `-1` accepts either state. Observed
	 *   probes are emitted through TAP diagnostics when the wait expires.
	 *
	 * @param sequence_id Last probe-log sequence observed before the expected probe.
	 * @param backend Backend IP/port endpoint expected to receive the probe.
	 * @param probe_kind Type of topology query expected.
	 * @param timeout_ms Maximum time to wait in milliseconds.
	 * @param encrypted Expected TLS state, or -1 to accept either state.
	 *
	 * @return EXIT_SUCCESS and the matching record; ETIMEDOUT and an empty record when
	 *   the deadline expires; EXIT_FAILURE and an empty record when log retrieval fails.
	 */
	rc_t<RDS_BGD_Probe_Log> wait_for_probe_log(
		uint64_t sequence_id,
		Endpoint backend,
		RDS_BGD_Probe_Kind probe_kind,
		uint32_t timeout_ms,
		int encrypted = -1
	);

private:
	/**
	 * @brief Builds the SQL predicate identifying one simulated backend.
	 *
	 * @param backend Backend IP/port endpoint to match.
	 *
	 * @return SQL predicate matching the backend control-table key.
	 */
	static string backend_predicate(Endpoint backend);

	/**
	 * @brief Executes simulator control statements in one transaction.
	 *
	 * @details Executes the supplied statements in order and commits only after every
	 *   statement succeeds. A statement or commit failure triggers a rollback.
	 *
	 * @param statements SQL statements to execute atomically.
	 *
	 * @return EXIT_SUCCESS when the transaction commits; EXIT_FAILURE otherwise.
	 */
	int execute_transaction(vector<string>& statements);
};

#endif  // TAP_RDS_BGD_SIMULATOR_H
