// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysqlx_sql.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mysqlx_5fsql_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mysqlx_5fsql_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "mysqlx.pb.h"
#include "mysqlx_datatypes.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mysqlx_5fsql_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mysqlx_5fsql_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mysqlx_5fsql_2eproto;
namespace Mysqlx {
namespace Sql {
class StmtExecute;
struct StmtExecuteDefaultTypeInternal;
extern StmtExecuteDefaultTypeInternal _StmtExecute_default_instance_;
class StmtExecuteOk;
struct StmtExecuteOkDefaultTypeInternal;
extern StmtExecuteOkDefaultTypeInternal _StmtExecuteOk_default_instance_;
}  // namespace Sql
}  // namespace Mysqlx
PROTOBUF_NAMESPACE_OPEN
template<> ::Mysqlx::Sql::StmtExecute* Arena::CreateMaybeMessage<::Mysqlx::Sql::StmtExecute>(Arena*);
template<> ::Mysqlx::Sql::StmtExecuteOk* Arena::CreateMaybeMessage<::Mysqlx::Sql::StmtExecuteOk>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Mysqlx {
namespace Sql {

// ===================================================================

class StmtExecute final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Mysqlx.Sql.StmtExecute) */ {
 public:
  inline StmtExecute() : StmtExecute(nullptr) {}
  ~StmtExecute() override;
  explicit PROTOBUF_CONSTEXPR StmtExecute(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StmtExecute(const StmtExecute& from);
  StmtExecute(StmtExecute&& from) noexcept
    : StmtExecute() {
    *this = ::std::move(from);
  }

  inline StmtExecute& operator=(const StmtExecute& from) {
    CopyFrom(from);
    return *this;
  }
  inline StmtExecute& operator=(StmtExecute&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StmtExecute& default_instance() {
    return *internal_default_instance();
  }
  static inline const StmtExecute* internal_default_instance() {
    return reinterpret_cast<const StmtExecute*>(
               &_StmtExecute_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StmtExecute& a, StmtExecute& b) {
    a.Swap(&b);
  }
  inline void Swap(StmtExecute* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StmtExecute* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StmtExecute* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StmtExecute>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StmtExecute& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StmtExecute& from) {
    StmtExecute::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StmtExecute* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Mysqlx.Sql.StmtExecute";
  }
  protected:
  explicit StmtExecute(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArgsFieldNumber = 2,
    kStmtFieldNumber = 1,
    kNamespaceFieldNumber = 3,
    kCompactMetadataFieldNumber = 4,
  };
  // repeated .Mysqlx.Datatypes.Any args = 2;
  int args_size() const;
  private:
  int _internal_args_size() const;
  public:
  void clear_args();
  ::Mysqlx::Datatypes::Any* mutable_args(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Mysqlx::Datatypes::Any >*
      mutable_args();
  private:
  const ::Mysqlx::Datatypes::Any& _internal_args(int index) const;
  ::Mysqlx::Datatypes::Any* _internal_add_args();
  public:
  const ::Mysqlx::Datatypes::Any& args(int index) const;
  ::Mysqlx::Datatypes::Any* add_args();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Mysqlx::Datatypes::Any >&
      args() const;

  // required bytes stmt = 1;
  bool has_stmt() const;
  private:
  bool _internal_has_stmt() const;
  public:
  void clear_stmt();
  const std::string& stmt() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stmt(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stmt();
  PROTOBUF_NODISCARD std::string* release_stmt();
  void set_allocated_stmt(std::string* stmt);
  private:
  const std::string& _internal_stmt() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stmt(const std::string& value);
  std::string* _internal_mutable_stmt();
  public:

  // optional string namespace = 3 [default = "sql"];
  bool has_namespace_() const;
  private:
  bool _internal_has_namespace_() const;
  public:
  void clear_namespace_();
  const std::string& namespace_() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_namespace_(ArgT0&& arg0, ArgT... args);
  std::string* mutable_namespace_();
  PROTOBUF_NODISCARD std::string* release_namespace_();
  void set_allocated_namespace_(std::string* namespace_);
  private:
  const std::string& _internal_namespace_() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_namespace_(const std::string& value);
  std::string* _internal_mutable_namespace_();
  public:

  // optional bool compact_metadata = 4 [default = false];
  bool has_compact_metadata() const;
  private:
  bool _internal_has_compact_metadata() const;
  public:
  void clear_compact_metadata();
  bool compact_metadata() const;
  void set_compact_metadata(bool value);
  private:
  bool _internal_compact_metadata() const;
  void _internal_set_compact_metadata(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Mysqlx.Sql.StmtExecute)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Mysqlx::Datatypes::Any > args_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stmt_;
    static const ::PROTOBUF_NAMESPACE_ID::internal::LazyString _i_give_permission_to_break_this_code_default_namespace__;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr namespace__;
    bool compact_metadata_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mysqlx_5fsql_2eproto;
};
// -------------------------------------------------------------------

class StmtExecuteOk final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:Mysqlx.Sql.StmtExecuteOk) */ {
 public:
  inline StmtExecuteOk() : StmtExecuteOk(nullptr) {}
  explicit PROTOBUF_CONSTEXPR StmtExecuteOk(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StmtExecuteOk(const StmtExecuteOk& from);
  StmtExecuteOk(StmtExecuteOk&& from) noexcept
    : StmtExecuteOk() {
    *this = ::std::move(from);
  }

  inline StmtExecuteOk& operator=(const StmtExecuteOk& from) {
    CopyFrom(from);
    return *this;
  }
  inline StmtExecuteOk& operator=(StmtExecuteOk&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StmtExecuteOk& default_instance() {
    return *internal_default_instance();
  }
  static inline const StmtExecuteOk* internal_default_instance() {
    return reinterpret_cast<const StmtExecuteOk*>(
               &_StmtExecuteOk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(StmtExecuteOk& a, StmtExecuteOk& b) {
    a.Swap(&b);
  }
  inline void Swap(StmtExecuteOk* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StmtExecuteOk* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StmtExecuteOk* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StmtExecuteOk>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const StmtExecuteOk& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const StmtExecuteOk& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Mysqlx.Sql.StmtExecuteOk";
  }
  protected:
  explicit StmtExecuteOk(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Mysqlx.Sql.StmtExecuteOk)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_mysqlx_5fsql_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StmtExecute

// optional string namespace = 3 [default = "sql"];
inline bool StmtExecute::_internal_has_namespace_() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool StmtExecute::has_namespace_() const {
  return _internal_has_namespace_();
}
inline void StmtExecute::clear_namespace_() {
  _impl_.namespace__.ClearToDefault(::Mysqlx::Sql::StmtExecute::Impl_::_i_give_permission_to_break_this_code_default_namespace__, GetArenaForAllocation());
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& StmtExecute::namespace_() const {
  // @@protoc_insertion_point(field_get:Mysqlx.Sql.StmtExecute.namespace)
  if (_impl_.namespace__.IsDefault()) return Impl_::_i_give_permission_to_break_this_code_default_namespace__.get();
  return _internal_namespace_();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StmtExecute::set_namespace_(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.namespace__.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Mysqlx.Sql.StmtExecute.namespace)
}
inline std::string* StmtExecute::mutable_namespace_() {
  std::string* _s = _internal_mutable_namespace_();
  // @@protoc_insertion_point(field_mutable:Mysqlx.Sql.StmtExecute.namespace)
  return _s;
}
inline const std::string& StmtExecute::_internal_namespace_() const {
  return _impl_.namespace__.Get();
}
inline void StmtExecute::_internal_set_namespace_(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.namespace__.Set(value, GetArenaForAllocation());
}
inline std::string* StmtExecute::_internal_mutable_namespace_() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.namespace__.Mutable(::Mysqlx::Sql::StmtExecute::Impl_::_i_give_permission_to_break_this_code_default_namespace__, GetArenaForAllocation());
}
inline std::string* StmtExecute::release_namespace_() {
  // @@protoc_insertion_point(field_release:Mysqlx.Sql.StmtExecute.namespace)
  if (!_internal_has_namespace_()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.namespace__.Release();
  return p;
}
inline void StmtExecute::set_allocated_namespace_(std::string* namespace_) {
  if (namespace_ != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.namespace__.SetAllocated(namespace_, GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Mysqlx.Sql.StmtExecute.namespace)
}

// required bytes stmt = 1;
inline bool StmtExecute::_internal_has_stmt() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool StmtExecute::has_stmt() const {
  return _internal_has_stmt();
}
inline void StmtExecute::clear_stmt() {
  _impl_.stmt_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& StmtExecute::stmt() const {
  // @@protoc_insertion_point(field_get:Mysqlx.Sql.StmtExecute.stmt)
  return _internal_stmt();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StmtExecute::set_stmt(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.stmt_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Mysqlx.Sql.StmtExecute.stmt)
}
inline std::string* StmtExecute::mutable_stmt() {
  std::string* _s = _internal_mutable_stmt();
  // @@protoc_insertion_point(field_mutable:Mysqlx.Sql.StmtExecute.stmt)
  return _s;
}
inline const std::string& StmtExecute::_internal_stmt() const {
  return _impl_.stmt_.Get();
}
inline void StmtExecute::_internal_set_stmt(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.stmt_.Set(value, GetArenaForAllocation());
}
inline std::string* StmtExecute::_internal_mutable_stmt() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.stmt_.Mutable(GetArenaForAllocation());
}
inline std::string* StmtExecute::release_stmt() {
  // @@protoc_insertion_point(field_release:Mysqlx.Sql.StmtExecute.stmt)
  if (!_internal_has_stmt()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.stmt_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stmt_.IsDefault()) {
    _impl_.stmt_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void StmtExecute::set_allocated_stmt(std::string* stmt) {
  if (stmt != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.stmt_.SetAllocated(stmt, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stmt_.IsDefault()) {
    _impl_.stmt_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Mysqlx.Sql.StmtExecute.stmt)
}

// repeated .Mysqlx.Datatypes.Any args = 2;
inline int StmtExecute::_internal_args_size() const {
  return _impl_.args_.size();
}
inline int StmtExecute::args_size() const {
  return _internal_args_size();
}
inline ::Mysqlx::Datatypes::Any* StmtExecute::mutable_args(int index) {
  // @@protoc_insertion_point(field_mutable:Mysqlx.Sql.StmtExecute.args)
  return _impl_.args_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Mysqlx::Datatypes::Any >*
StmtExecute::mutable_args() {
  // @@protoc_insertion_point(field_mutable_list:Mysqlx.Sql.StmtExecute.args)
  return &_impl_.args_;
}
inline const ::Mysqlx::Datatypes::Any& StmtExecute::_internal_args(int index) const {
  return _impl_.args_.Get(index);
}
inline const ::Mysqlx::Datatypes::Any& StmtExecute::args(int index) const {
  // @@protoc_insertion_point(field_get:Mysqlx.Sql.StmtExecute.args)
  return _internal_args(index);
}
inline ::Mysqlx::Datatypes::Any* StmtExecute::_internal_add_args() {
  return _impl_.args_.Add();
}
inline ::Mysqlx::Datatypes::Any* StmtExecute::add_args() {
  ::Mysqlx::Datatypes::Any* _add = _internal_add_args();
  // @@protoc_insertion_point(field_add:Mysqlx.Sql.StmtExecute.args)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Mysqlx::Datatypes::Any >&
StmtExecute::args() const {
  // @@protoc_insertion_point(field_list:Mysqlx.Sql.StmtExecute.args)
  return _impl_.args_;
}

// optional bool compact_metadata = 4 [default = false];
inline bool StmtExecute::_internal_has_compact_metadata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool StmtExecute::has_compact_metadata() const {
  return _internal_has_compact_metadata();
}
inline void StmtExecute::clear_compact_metadata() {
  _impl_.compact_metadata_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool StmtExecute::_internal_compact_metadata() const {
  return _impl_.compact_metadata_;
}
inline bool StmtExecute::compact_metadata() const {
  // @@protoc_insertion_point(field_get:Mysqlx.Sql.StmtExecute.compact_metadata)
  return _internal_compact_metadata();
}
inline void StmtExecute::_internal_set_compact_metadata(bool value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.compact_metadata_ = value;
}
inline void StmtExecute::set_compact_metadata(bool value) {
  _internal_set_compact_metadata(value);
  // @@protoc_insertion_point(field_set:Mysqlx.Sql.StmtExecute.compact_metadata)
}

// -------------------------------------------------------------------

// StmtExecuteOk

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Sql
}  // namespace Mysqlx

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mysqlx_5fsql_2eproto
