services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/proxysql:cached
    working_dir: /proxysql
    init: true
    command: sleep infinity

  mariadb:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
