//#ifdef __cplusplus
#include "MySQL_Data_Stream.h"
#include "MySQL_Session.h"
#include "MySQL_Thread.h"
#include "gen_utils.h"
#include "mysql_backend.h"
#include "mysql_connection.h"
#include "query_cache.hpp"
#include "sqlite3db.h"
//#include "simple_kv.h"
#include "MySQL_Authentication.hpp"
#include "MySQL_HostGroups_Manager.h"
#include "MySQL_Logger.hpp"
#include "MySQL_Monitor.hpp"
#include "MySQL_PreparedStatement.h"
#include "MySQL_Protocol.h"
#include "StatCounters.h"
#include "configfile.hpp"
#include "fileutils.hpp"
#include "proxysql_admin.h"
#include "query_processor.h"
#undef swap
#undef min
#undef max
//#include <memory>
#include <stdio.h>
//#include <algorithm>
//#include <functional>
//#include <type_traits>
//#include <iosfwd>
#include <map>
#include <unordered_map>
//#include <set>
//#include <sstream>
//#include <string>
//#include <utility>
//#include <vector>
//#endif /* __cplusplus */
