#!/usr/bin/env bash
set -euo pipefail

# Runs clang-tidy and cppcheck for the initial scope (lib/ and include/)
# Expectation: compile_commands.json exists in repo root (generated by generate-compile-commands.sh)

SCOPE_GLOB="lib/**/*.cpp include/**/*.h"
CLANG_TIDY_BIN=${CLANG_TIDY_BIN:-clang-tidy}
CPPCHECK_BIN=${CPPCHECK_BIN:-cppcheck}

if [ ! -f compile_commands.json ]; then
  echo "compile_commands.json not found. Run scripts/lint/generate-compile-commands.sh first." >&2
  exit 1
fi

mkdir -p lint
echo "Running clang-tidy..."
# Export fixes to a YAML file per run; list files explicitly from git to scope to lib/ and include/
FILES=$(git ls-files lib | tr '\n' ' ')
${CLANG_TIDY_BIN} -p . -checks='clang-analyzer-*,bugprone-*,performance-*,modernize-*,readability-*' --export-fixes=lint/clang-tidy-fixes.yaml ${FILES} || true

echo "Running cppcheck..."
${CPPCHECK_BIN} --enable=warning,performance,portability,style --std=c++17 --project=compile_commands.json --inline-suppr 2> lint/cppcheck-output.txt || true

echo "Normalizing outputs..."
python3 scripts/lint/normalize-clang-tidy.py lint/clang-tidy-fixes.yaml > lint/clang-tidy.txt || true
python3 scripts/lint/normalize-cppcheck.py lint/cppcheck-output.txt > lint/cppcheck.txt || true

echo "Local lint run complete. Reports written to lint/clang-tidy.txt and lint/cppcheck.txt"
