name: CI-3p-php-pdo-mysql

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ "CI-builds" ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    uses: sysown/proxysql/.github/workflows/ci-3p-php-pdo-mysql.yml@GH-Actions
    secrets: inherit
    
