name: CI-ai-g1

on:
  workflow_call:
    inputs:
      trigger:
        type: string

permissions: write-all

jobs:
  tests:
    uses: sysown/proxysql/.github/workflows/ci-ai-gcov.yml@GH-Actions
    with:
      trigger: ${{ inputs.trigger }}
      tap_group: ai-g1
      infra_id: ci-ai-g1
    secrets: inherit
