name: CI-mysql90-binlog-g1

on:
  workflow_call:
    inputs:
      trigger:
        type: string

      consumer_id:
        type: string
        default: run
      control_ref:
        type: string
        default: GH-Actions
      producer_run_id:
        type: string
        default: ''
      producer_attempt:
        type: string
        default: ''
permissions:
  actions: write
  pull-requests: read
  checks: write
  contents: read
  id-token: write
  packages: read

jobs:
  tests:
    uses: ./.github/workflows/ci-ai-gcov.yml
    with:
      trigger: ${{ inputs.trigger }}
      tap_group: mysql90-binlog-g1
      infra_id: ci-mysql90-binlog-g1
      consumer_id: ${{ inputs.consumer_id }}
      control_ref: ${{ inputs.control_ref }}
      producer_run_id: ${{ inputs.producer_run_id }}
      producer_attempt: ${{ inputs.producer_attempt }}
