name: CI-push-ci-base-image

on:
  push:
    branches:
      - v3.0
    paths:
      - test/infra/docker-base/Dockerfile
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sysown/proxysql-ci-base

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Log in to Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/v3.0' }}
            type=ref,event=branch,prefix=branch-
            type=sha,prefix=

      - name: Build and push Docker image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: test/infra/docker-base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
