name: CI-trigger

on:
  workflow_dispatch:
  workflow_call:

jobs:
  trigger:
    runs-on: ubuntu-22.04

    steps:
    - name: Trigger workflow_run[in_progress]
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set +e
        #set -x

        #RUNNAME="${{ github.head_ref || github.ref_name }} CI-builds ${{ github.event.after || github.sha }}"
        RUNNAME="${{ github.head_ref || github.ref_name }} CI-builds ${{ github.sha }}"
        echo "Get run id: '${RUNNAME}' ..."
        sleep 5
        RUNID=$(gh -R ${{ github.repository }} run list -w CI-builds -s in_progress | grep "${RUNNAME}" | grep -Po '(?<=workflow_run)\s+\d+')
        while [[ -z ${RUNID} ]]; do
          sleep 5
          RUNID=$(gh -R ${{ github.repository }} run list -w CI-builds -s in_progress | grep "${RUNNAME}" | grep -Po '(?<=workflow_run)\s+\d+')
        done
        echo "Got run id: '${RUNNAME}' : '${RUNID}'"
        
        echo "Trigger workflow_run[in_progress]: '${RUNNAME}'"
        sleep 5
        # this blocks until the run is finished
        gh -R ${{ github.repository }} run watch -i 30 ${RUNID} >/dev/null
        sleep 5

    - name: Trigger workflow_run[completed]
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Cleanup skipped ..."
        gh -R ${{ github.repository }} run list -s skipped -L 100 --json databaseId  -q '.[].databaseId' | xargs -r -n1 gh -R ${{ github.repository }} run delete
        echo "Triggered workflow_run[completed]: '${{ github.ref_name }} ${{ github.workflow }} ${{ github.sha }}'"
        
